{{ if ( and .Values.keycloak.enabled (not (.Values.keycloakPostInstall).disabled ) ) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: post-install-keycloak-config
  labels:
    app.kubernetes.io/name: post-install-keycloak-config
    app.kubernetes.io/component: sso
    app.kubernetes.io/part-of: sso
data:
  client-frontend.json: |
    {
      "clientId": "frontend",
      "clientAuthenticatorType": "client-secret",
      "enabled": true,
      "publicClient": true,
      "implicitFlowEnabled": true,
      "standardFlowEnabled": true,
      "directAccessGrantsEnabled": false,
      "serviceAccountsEnabled": false,
      "fullScopeAllowed": true,
      "webOrigins": [
        "*"
      ],
      "defaultClientScopes": [
        "email",
        "profile",
        "roles",
        "web-origins"
      ],
      "optionalClientScopes": [
        "address",
        "microprofile-jwt",
        "offline_access",
        "phone"
      ],
      "defaultRoles": [
        "chicken-user"
      ],
      "attributes": {
        "access.token.lifespan": "300",
        "post.logout.redirect.uris": "+"
      }
    }
  client-walker.json: |
    {
      "clientId": "walker",
      "clientAuthenticatorType": "client-secret",
      "enabled": true,
      "publicClient": false,
      "implicitFlowEnabled": false,
      "standardFlowEnabled": false,
      "directAccessGrantsEnabled": false,
      "serviceAccountsEnabled": true,
      "fullScopeAllowed": true,
      "defaultClientScopes": [
        "email",
        "profile",
        "roles",
        "web-origins"
      ],
      "optionalClientScopes": [
        "address",
        "microprofile-jwt",
        "offline_access",
        "phone"
      ],
      "defaultRoles": [
        "chicken-user",
        "chicken-manager"
      ],
      "attributes": {
        "access.token.lifespan": "300",
        "post.logout.redirect.uris": "+"
      }
    }
  client-testing-manager.json: |
    {
      "clientId": "testing-manager",
      "clientAuthenticatorType": "client-secret",
      "enabled": true,
      "publicClient": false,
      "implicitFlowEnabled": false,
      "standardFlowEnabled": false,
      "directAccessGrantsEnabled": false,
      "serviceAccountsEnabled": true,
      "fullScopeAllowed": true,
      "defaultClientScopes": [
        "email",
        "profile",
        "roles",
        "web-origins"
      ],
      "optionalClientScopes": [
        "address",
        "microprofile-jwt",
        "offline_access",
        "phone"
      ],
      "defaultRoles": [
        "chicken-user",
        "chicken-manager"
      ],
      "attributes": {
        "access.token.lifespan": "300",
        "post.logout.redirect.uris": "+"
      }
    }
  client-testing-user.json: |
    {
      "clientId": "testing-user",
      "clientAuthenticatorType": "client-secret",
      "enabled": true,
      "publicClient": false,
      "implicitFlowEnabled": false,
      "standardFlowEnabled": false,
      "directAccessGrantsEnabled": false,
      "serviceAccountsEnabled": true,
      "fullScopeAllowed": true,
      "defaultClientScopes": [
        "email",
        "profile",
        "roles",
        "web-origins"
      ],
      "optionalClientScopes": [
        "address",
        "microprofile-jwt",
        "offline_access",
        "phone"
      ],
      "defaultRoles": [
        "chicken-user",
        "chicken-manager"
      ],
      "attributes": {
        "access.token.lifespan": "300",
        "post.logout.redirect.uris": "+"
      }
    }
{{ end }}
