release: 0.1.0-nightly.9c8ef105
domain: dev.trustification.dev
replicas: 1
imagePullPolicy: IfNotPresent
region: eu-west-1
bombastic:
  bucket: bombastic-dev
  credentials: bombastic-credentials-secret
  storedTopic: sbom-stored-dev
  indexedTopic: sbom-indexed-dev
  failedTopic: sbom-failed-dev
vexination:
  bucket: vexination-dev
  credentials: vexination-credentials-secret
  storedTopic: vex-stored-dev
  indexedTopic: vex-indexed-dev
  failedTopic: vex-failed-dev
