release: 0.1.0-nightly.8c8c127c
domain: trustification.dev
replicas: 2
imagePullPolicy: IfNotPresent
region: eu-west-1
csafSnapshot: true
bombastic:
  bucket: bombastic-prod
  credentials: bombastic-credentials-secret
  storedTopic: sbom-stored-prod
  indexedTopic: sbom-indexed-prod
  failedTopic: sbom-failed-prod
  exporterTopic: sbom-guac-prod
vexination:
  bucket: vexination-prod
  credentials: vexination-credentials-secret
  storedTopic: vex-stored-prod
  indexedTopic: vex-indexed-prod
  failedTopic: vex-failed-prod
  # TODO: Use when key issues are resolved source: https://www.redhat.com/.well-known/csaf/provider-metadata.json
  source: http://csaf-snapshot:8080/metadata/provider-metadata.json
  exporterTopic: vex-guac-prod
