release: 0.1.0-nightly.76e2f277
domain: staging.trustification.dev
replicas: 1
imagePullPolicy: IfNotPresent
region: eu-west-1
csafSnapshot: true
bombastic:
  bucket: bombastic-staging
  credentials: bombastic-credentials-secret
  apiSecret: bombastic-api-secret
  storedTopic: sbom-stored-staging
  indexedTopic: sbom-indexed-staging
  failedTopic: sbom-failed-staging
  exporterTopic: vex-guac-staging
vexination:
  bucket: vexination-staging
  credentials: vexination-credentials-secret
  apiSecret: vexination-api-secret
  storedTopic: vex-stored-staging
  indexedTopic: vex-indexed-staging
  failedTopic: vex-failed-staging
  source: http://csaf-snapshot:8080/metadata/provider-metadata.json
  exporterTopic: vex-guac-staging
