release: 0.1.0-nightly.9c22a3bc
domain: staging.trustification.dev
replicas: 1
imagePullPolicy: IfNotPresent
region: eu-west-1
enableWalkers: false
enableTests: true
spog:
  uiConfig: config/staging/spog-ui.yaml
bombastic:
  bucket: bombastic-staging
  credentials: bombastic-credentials-secret
  storedTopic: sbom-stored-staging
  indexedTopic: sbom-indexed-staging
  failedTopic: sbom-failed-staging
  exporterTopic: sbom-guac-staging
  indexMode: file
vexination:
  bucket: vexination-staging
  credentials: vexination-credentials-secret
  storedTopic: vex-stored-staging
  indexedTopic: vex-indexed-staging
  failedTopic: vex-failed-staging
  source: https://www.redhat.com/.well-known/csaf/provider-metadata.json
  exporterTopic: vex-guac-staging
  indexMode: file
keycloak:
  enabled: true
  production: true
  proxy: reencrypt
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  auth:
    adminUser: admin
    existingSecret: sso-admin
    passwordSecretKey: password
  tls:
    enabled: true
    existingSecret: sso-tls
    usePem: true
  service:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: sso-tls
  ingress:
    enabled: true
    ingressClassName: openshift-default
    hostname: sso.staging.trustification.dev
    servicePort: https
    annotations:
      route.openshift.io/termination: reencrypt
  postgresql:
    primary:
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
    auth:
      existingSecret: sso-postgres
keycloakRealm:
  redirectUris:
    - http://localhost:*
    - https://staging.trustification.dev
    - https://staging.trustification.dev/*
    - https://sbom.staging.trustification.dev
    - https://sbom.staging.trustification.dev/*
    - https://vex.staging.trustification.dev
    - https://vex.staging.trustification.dev/*
    - https://trustification-*-preview.surge.sh
    - https://trustification-*-preview.surge.sh/*
authentication:
  issuerUrl: https://sso.staging.trustification.dev/realms/chicken
  clientIds:
    - frontend
    - walker
oidcClients:
  frontend:
    clientId:
      value: frontend
  walker:
    clientSecret:
      valueFrom:
        secretKeyRef:
          name: oidc-client-walker
          key: client-secret
  testing-manager:
    clientSecret:
      valueFrom:
        secretKeyRef:
          name: oidc-client-testing-manager
          key: client-secret
  testing-user:
    clientSecret:
      valueFrom:
        secretKeyRef:
          name: oidc-client-testing-user
          key: client-secret
