release: 0.1.0-nightly.45eb4acc
domain: staging.trustification.dev
replicas: 1
imagePullPolicy: IfNotPresent
region: eu-west-1
csafSnapshot: true
spog:
  uiConfig: config/staging/spog-ui.yaml
bombastic:
  bucket: bombastic-staging
  credentials: bombastic-credentials-secret
  apiSecret: bombastic-api-secret
  storedTopic: sbom-stored-staging
  indexedTopic: sbom-indexed-staging
  failedTopic: sbom-failed-staging
  exporterTopic: vex-guac-staging
vexination:
  bucket: vexination-staging
  credentials: vexination-credentials-secret
  apiSecret: vexination-api-secret
  storedTopic: vex-stored-staging
  indexedTopic: vex-indexed-staging
  failedTopic: vex-failed-staging
  source: http://csaf-snapshot:8080/metadata/provider-metadata.json
  exporterTopic: vex-guac-staging
keycloak:
  enabled: true
  production: true
  proxy: reencrypt
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  auth:
    existingSecret: sso-admin
    passwordSecretKet: password
  tls:
    enabled: true
    existingSecret: sso-tls
    usePem: true
  service:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: sso-tls
  ingress:
    enabled: true
    ingressClassName: openshift-default
    hostname: sso.staging.trustification.dev
    annotations:
      route.openshift.io/termination: reencrypt
  postgresql:
    primary:
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
    auth:
      existingSecret: sso-postgres
