{{ if .Values.enableWalkers }}
apiVersion: batch/v1
kind: Job
metadata:
  name: bombastic-walker
  labels:
    app.kubernetes.io/name: bombastic-walker
    app.kubernetes.io/component: walker
    app.kubernetes.io/part-of: trustification
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bombastic-walker
        app.kubernetes.io/component: walker
        app.kubernetes.io/part-of: trustification
    spec:
      restartPolicy: Never
      volumes:
        - name: run
          emptyDir: {}
      containers:
        - image: {{ .Values.trustImage }}:{{ .Values.release }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: walker
          command: ["/trust"]
          args:
            - "bombastic"
            - "walker"
            - "--workdir"
            - "/run"
            - "--scripts-path"
            - "/usr/bin"
            # we use the external URL here, since it has a public certificate, otherwise we would need to adapt
            # the bombastic walker to use our TLS setup, right now it relies on a script and curl.
            - "--bombastic-url"
            - "https://sbom.{{ .Values.domain }}"
          env:
            {{ include "trustification.authentication-client" ( dict "root" . "clientId" "walker" ) | nindent 12 }}
          volumeMounts:
            - name: run
              mountPath: /run
{{ end }}
