apiVersion: batch/v1
kind: Job
metadata:
  name: bombastic-walker
  labels:
    app.kubernetes.io/name: bombastic-walker
    app.kubernetes.io/component: walker
    app.kubernetes.io/part-of: bombastic
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bombastic-walker
        app.kubernetes.io/component: walker
        app.kubernetes.io/part-of: bombastic
    spec:
      restartPolicy: Never
      volumes:
        - name: run
          emptyDir: {}
      containers:
        # - image: ghcr.io/trustification/trust:{{ .Values.release }}
        - image: ghcr.io/trustification/trust-bombastic-feeder-tmp:latest
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: walker
          command: ["/walker.sh"]
          args: ["http://bombastic"]
          volumeMounts:
            - name: run
              mountPath: /run
