apiVersion: v1
kind: ConfigMap
metadata:
  name: spog-api
  labels:
    app.kubernetes.io/name: spog-api
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: spog
data:
  spog-ui.yaml: |-
    {{- .Files.Get .Values.spog.uiConfig | nindent 4 }}
