apiVersion: apps/v1
kind: Deployment
metadata:
  name: spog-api
  labels:
    app.kubernetes.io/name: spog-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: spog
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: spog-api
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: spog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spog-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: spog
    spec:
      containers:
        - image: ghcr.io/trustification/trust:{{ .Values.release }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: service
          command: ["/trust"]
          args: ["spog", "api", "-p", "8080", "--bombastic-url", "http://bombastic-api", "--vexination-url", "http://vexination-api", "--authentication-issuer-url", "http://trustification-staging-keycloak/realms/chicken", "--authentication-client-id", "frontend" ]
          env:
            - name: RUST_LOG
              value: info
            - name: INFRASTRUCTURE_ENABLED
              value: "true"
            - name: INFRASTRUCTURE_BIND
              value: "[::]:9010"
            - name: SPOG_UI_CONFIG
              value: /etc/spog/spog-ui.yaml
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9010
              protocol: TCP
              name: infra
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9010
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9010
            initialDelaySeconds: 2
          startupProbe:
            httpGet:
              path: /health/startup
              port: 9010
          volumeMounts:
            - mountPath: /etc/spog
              name: config
      volumes:
        - name: config
          configMap:
            name: spog-api
