{{ if .Values.enableWalkers }}
apiVersion: batch/v1
kind: Job
metadata:
  name: vexination-walker
  labels:
    app.kubernetes.io/name: vexination-walker
    app.kubernetes.io/component: walker
    app.kubernetes.io/part-of: trustification
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vexination-walker
        app.kubernetes.io/component: walker
        app.kubernetes.io/part-of: trustification
    spec:
      restartPolicy: Never
      containers:
        - image: {{ .Values.trustImage }}:{{ .Values.release }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: walker
          command: ["/trust"]
          args: ["vexination", "walker", "-3", "--source", "{{ .Values.vexination.source }}"]
          env:
            - name: RUST_LOG
              value: info
            - name: STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.vexination.credentials }}"
                  key: access-key-id
            - name: STORAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.vexination.credentials }}"
                  key: secret-access-key
            - name: STORAGE_REGION
              value: "{{ .Values.region }}"
            - name: STORAGE_BUCKET
              value: "{{ .Values.vexination.bucket }}"
{{ end }}
