apiVersion: batch/v1
kind: Job
metadata:
  name: vexination-walker
  labels:
    app.kubernetes.io/name: vexination-walker
    app.kubernetes.io/component: walker
    app.kubernetes.io/part-of: vexination
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vexination-walker
        app.kubernetes.io/component: walker
        app.kubernetes.io/part-of: vexination
    spec:
      restartPolicy: Never
      containers:
        - image: ghcr.io/trustification/trust:{{ .Values.release }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: walker
          command: ["/trust"]
          args: ["vexination", "walker", "-3", "--storage-bucket", "{{ .Values.vexination.bucket }}", "--source", "{{ .Values.vexination.source }}"]
          env:
            - name: RUST_LOG
              value: info
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.vexination.credentials }}"
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.vexination.credentials }}"
                  key: secret-access-key
            - name: REGION
              value: "{{ .Values.region }}"
