{{ if .Values.collector.nvd.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: collector-nvd
    app.kubernetes.io/component: collector
    app.kubernetes.io/part-of: trustification
  name: collector-nvd
spec:
  ports:
  - name: endpoint
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: collector-nvd
    app.kubernetes.io/component: collector
    app.kubernetes.io/part-of: trustification
  type: ClusterIP
{{ end }}
