$schema: "https://raw.githubusercontent.com/trustification/trustification/main/spog/model/schema/config.json"

bombastic:

  filters:
    categories:

      - label: Products
        options:

          - type: check
            label: UBI 7
            id: ubi7
            terms:
              - '"pkg:oci/redhat/ubi7"'

          - type: check
            label: UBI 8
            id: ubi8
            terms:
              - '"pkg:oci/redhat/ubi8"'

          - type: check
            label: UBI 9
            id: ubi9
            terms:
              - '"pkg:oci/redhat/ubi9"'

          - type: divider

          - type: check
            label: Red Hat Enterprise Linux 7
            id: rhel7
            terms:
              - '"cpe:/o:redhat:enterprise_linux:7"'

          - type: check
            label: Red Hat Enterprise Linux 8
            id: rhel8
            terms:
              - '"cpe:/o:redhat:enterprise_linux:8"'

          - type: check
            label: Red Hat Enterprise Linux 9
            id: rhel9
            terms:
              - '"cpe:/o:redhat:enterprise_linux:9"'

          - type: divider

          - type: check
            label: Ansible
            id: ansible
            terms:
              - '"cpe:/a:redhat:ansible_automation_platform"'

          - type: check
            label: AMQ
            id: amq
            terms:
              - '"cpe:/a:redhat:amq" OR "amq-"'

          - type: check
            label: Quarkus
            id: quarkus
            terms:
              - '"quarkus"'

      - label: Type
        options:
          - type: check
            label: Container
            id: is_container
            terms:
              - 'type:oci'

      - label: Suppliers
        options:
          - type: check
            label: Red Hat
            id: supplier_redhat
            terms:
              - 'supplier:"Organization: Red Hat"'

      - label: Created on
        options:
          - type: select
            group: created-on
            default: any
            options:
              - id: last-week
                label: Last 7 days
                script: |
                  const end = new Date();
                  const start = new Date(end.getTime() - (7 * 24 * 60 * 60 * 1000));
                  [
                    "created:" + 
                    start.toLocaleString("default", { year: "numeric" }) + "-" +
                    start.toLocaleString("default", { month: "2-digit" }) + "-" +
                    start.toLocaleString("default", { day: "2-digit" }) + ".." +
                    end.toLocaleString("default", { year: "numeric" }) + "-" +
                    end.toLocaleString("default", { month: "2-digit" }) + "-" +
                    end.toLocaleString("default", { day: "2-digit" })
                  ];
              - id: last-month
                label: Last 30 days
                script: |
                  const end = new Date();
                  const start = new Date(end.getTime() - (30 * 24 * 60 * 60 * 1000));
                  [
                    "created:" + 
                    start.toLocaleString("default", { year: "numeric" }) + "-" +
                    start.toLocaleString("default", { month: "2-digit" }) + "-" +
                    start.toLocaleString("default", { day: "2-digit" }) + ".." +
                    end.toLocaleString("default", { year: "numeric" }) + "-" +
                    end.toLocaleString("default", { month: "2-digit" }) + "-" +
                    end.toLocaleString("default", { day: "2-digit" })
                  ];
              - id: this-year
                label: This year
                script: |
                  const date = new Date();
                  const start = new Date(date.getFullYear(), 0, 1);
                  const end = new Date(date.getFullYear()+1, 0, 1);
                  [
                    "created:" + 
                    start.toLocaleString("default", { year: "numeric" }) + "-" +
                    start.toLocaleString("default", { month: "2-digit" }) + "-" +
                    start.toLocaleString("default", { day: "2-digit" }) + ".." +
                    end.toLocaleString("default", { year: "numeric" }) + "-" +
                    end.toLocaleString("default", { month: "2-digit" }) + "-" +
                    end.toLocaleString("default", { day: "2-digit" })
                  ];
              - id: "2022"
                label: "2022"
                terms:
                  - 'created:2022-01-01..2023-01-01'
              - id: "2021"
                label: "2021"
                terms:
                  - 'created:2021-01-01..2022-01-01'
              - id: "any"
                label: "Any time"

vexination:

  filters:
    categories:
      - label: Severity
        options:
          - type: check
            id: low
            label: |
              <span class="tc-c-severity">
                  <span class="tc-c-severity__icon"> <span class="tc-m-severity-low"> <i class="fa fa-shield-halved"></i> </span></span>
                  <span class="tc-c-severity__text"> Low </span>
              </span>
            terms:
              - "severity:Low"
          - type: check
            id: moderate
            label: |
              <span class="tc-c-severity">
                  <span class="tc-c-severity__icon"> <span class="tc-m-severity-moderate"> <i class="fa fa-shield-halved"></i> </span></span>
                  <span class="tc-c-severity__text"> Moderate </span>
              </span>
            terms:
              - "severity:Moderate"
          - type: check
            id: important
            label: |
              <span class="tc-c-severity">
                  <span class="tc-c-severity__icon"> <span class="tc-m-severity-important"> <i class="fa fa-shield-halved"></i> </span></span>
                  <span class="tc-c-severity__text"> Important </span>
              </span>
            terms:
              - "severity:Important"
          - type: check
            id: critical
            label: |
              <span class="tc-c-severity">
                  <span class="tc-c-severity__icon"> <span class="tc-m-severity-critical"> <i class="fa fa-shield-halved"></i> </span></span>
                  <span class="tc-c-severity__text"> Critical </span>
              </span>
            terms:
              - "severity:Critical"

      - label: Products
        options:
          - type: check
            id: rhel7
            label: Red Hat Enterprise Linux 7
            terms:
              - '( "cpe:/o:redhat:rhel_eus:7" in:package )'

          - type: check
            id: rhel8
            label: Red Hat Enterprise Linux 8
            terms:
              - '( "cpe:/o:redhat:rhel_eus:8" in:package )'

          - type: check
            id: rhel9
            label: Red Hat Enterprise Linux 9
            terms:
              - '( "cpe:/a:redhat:enterprise_linux:9" in:package )'

          - type: divider

          - type: check
            id: ocp3
            label: OpenShift Container Platform 3
            terms:
              - '( "cpe:/a:redhat:openshift:3" in:package )'

          - type: check
            id: ocp4
            label: OpenShift Container Platform 4
            terms:
              - '( "cpe:/a:redhat:openshift:4" in:package )'

      - label: Revisions
        options:
          - type: select
            group: release
            default: any
            options:
              - id: last-week
                label: Last 7 days
                script: |
                  const end = new Date();
                  const start = new Date(end.getTime() - (7 * 24 * 60 * 60 * 1000));
                  [
                    "release:" +
                    start.toLocaleString("default", { year: "numeric" }) + "-" +
                    start.toLocaleString("default", { month: "2-digit" }) + "-" +
                    start.toLocaleString("default", { day: "2-digit" }) + ".." +
                    end.toLocaleString("default", { year: "numeric" }) + "-" +
                    end.toLocaleString("default", { month: "2-digit" }) + "-" +
                    end.toLocaleString("default", { day: "2-digit" })
                  ];
              - id: last-month
                label: Last 30 days
                script: |
                  const end = new Date();
                  const start = new Date(end.getTime() - (30 * 24 * 60 * 60 * 1000));
                  [
                    "release:" +
                    start.toLocaleString("default", { year: "numeric" }) + "-" +
                    start.toLocaleString("default", { month: "2-digit" }) + "-" +
                    start.toLocaleString("default", { day: "2-digit" }) + ".." +
                    end.toLocaleString("default", { year: "numeric" }) + "-" +
                    end.toLocaleString("default", { month: "2-digit" }) + "-" +
                    end.toLocaleString("default", { day: "2-digit" })
                  ];
              - id: this-year
                label: This year
                script: |
                  const date = new Date();
                  const start = new Date(date.getFullYear(), 0, 1);
                  const end = new Date(date.getFullYear()+1, 0, 1);
                  [
                    "release:" +
                    start.toLocaleString("default", { year: "numeric" }) + "-" +
                    start.toLocaleString("default", { month: "2-digit" }) + "-" +
                    start.toLocaleString("default", { day: "2-digit" }) + ".." +
                    end.toLocaleString("default", { year: "numeric" }) + "-" +
                    end.toLocaleString("default", { month: "2-digit" }) + "-" +
                    end.toLocaleString("default", { day: "2-digit" })
                  ];
              - id: "2022"
                label: "2022"
                terms:
                  - 'release:2022-01-01..2023-01-01'
              - id: "2021"
                label: "2021"
                terms:
                  - 'release:2021-01-01..2022-01-01'
              - id: "any"
                label: "Any time"

scanner:
  documentationUrl: https://red.ht/trusted
  welcomeHint:
    title: |
      <h2 class="pf-v5-c-title pf-m-2xl" style="text-align: center;">
        Receive a detailed summary of your SBOM stack including:
      </h2>
    body: |
      <div class="pf-v5-l-flex pf-m-gutter">
        <div class="pf-v5-l-flex pf-m-flex-1 pf-m-column pf-v5-u-p-xl">
          <div class="pf-v5-l-flex__item pf-m-align-self-center"><img width="64" src="branding/Icon-Red_Hat-Clipboard_Checklist-A-Red-RGB.svg"/></div>
          <div class="pf-v5-l-flex__item pf-m-align-self-center pf-v5-u-font-family-heading pf-v5-u-font-size-lg" style="width: 192px; text-align: center;">Security issues</div>
        </div>
        <div class="pf-v5-c-divider pf-m-vertical pf-m-inset-md" role="separator"></div>
        <div class="pf-v5-l-flex pf-m-flex-1 pf-m-column pf-v5-u-p-xl">
          <div class="pf-v5-l-flex__item pf-m-align-self-center"><img width="64" src="branding/Icon-Red_Hat-Vulnerability-A-Red-RGB.svg"/></div>
          <div class="pf-v5-l-flex__item pf-m-align-self-center pf-v5-u-font-family-heading pf-v5-u-font-size-lg" style="width: 192px; text-align: center;">Licenses</div>
        </div>
        <div class="pf-v5-c-divider pf-m-vertical pf-m-inset-md" role="separator"></div>
        <div class="pf-v5-l-flex pf-m-flex-1 pf-m-column pf-v5-u-p-xl">
          <div class="pf-v5-l-flex__item pf-m-align-self-center"><img width="64" src="branding/Icon-Red_Hat-Bug-A-Red-RGB.svg"/></div>
          <div class="pf-v5-l-flex__item pf-m-align-self-center pf-v5-u-font-family-heading pf-v5-u-font-size-lg" style="width: 192px; text-align: center;">Dependency details</div>
        </div>
      </div>

landingPage:
  headerContent: |
    <section
      class="pf-v5-c-page__main-section pf-m-light pf-m-shadow-bottom"
      style="
        background-image: url('branding/CND-AppSpeed-Keyart-2_at_2x.png');
        background-repeat: no-repeat;
        background-position: right;
        background-size: contain;
      "
    >
      <div class="pf-v5-l-grid pf-m-gutter">
        <div class="pf-v5-l-grid__item pf-m-8-col">
          <div class="pf-v5-c-content">
            <h1 class="pf-v5-c-title pf-m-2xl">Trusted Content</h1>
            <p class="pf-v5-u-color-200">A managed service for software supply chain security</p>
            <p>
              The Trusted Content service brings awareness to and remediation of Open Source Software (OSS) vulnerabilities that are discovered within the software supply chain.
              The Trusted Content service works within the software supply chain by helping developers to identify, and resolve security vulnerabilities during their development cycle.
            </p>
          </div>
        </div>
      </div>
    </section>

  beforeInnerContent: |
    <div class="pf-v5-u-mt-xl"></div>

  afterInnerContent: |
    <div class="pf-v5-l-bullseye pf-v5-u-mt-xl">
      <div class="pf-v5-l-bullseye__item">
        <div class="pf-v5-l-flex pf-m-gutter">
          <div class="pf-v5-l-flex pf-m-column">
            <div class="pf-v5-l-flex__item pf-m-align-self-center"><img width="64" src="branding/Icon-Red_Hat-Clipboard_Checklist-A-Red-RGB.svg"/></div>
            <div class="pf-v5-l-flex__item pf-m-align-self-center" style="width: 192px; text-align: center;">I need an SBOM for…</div>
          </div>
          <div class="pf-v5-l-flex pf-m-column">
            <div class="pf-v5-l-flex__item pf-m-align-self-center"><img width="64" src="branding/Icon-Red_Hat-Vulnerability-A-Red-RGB.svg"/></div>
            <div class="pf-v5-l-flex__item pf-m-align-self-center" style="width: 192px; text-align: center;">I have an SBOM and need vulnerability information</div>
          </div>
          <div class="pf-v5-l-flex pf-m-column">
            <div class="pf-v5-l-flex__item pf-m-align-self-center"><img width="64" src="branding/Icon-Red_Hat-Bug-A-Red-RGB.svg"/></div>
            <div class="pf-v5-l-flex__item pf-m-align-self-center" style="width: 192px; text-align: center;">I need information on a specific vulnerability</div>
          </div>
          <div class="pf-v5-l-flex pf-m-column">
            <div class="pf-v5-l-flex__item pf-m-align-self-center"><img width="64" src="branding/Icon-Red_Hat-Catalog-A-Red-RGB.svg"/></div>
            <div class="pf-v5-l-flex__item pf-m-align-self-center" style="width: 192px; text-align: center;">I want to browse by category: UBI, RHEL, …</div>
          </div>
        </div>
      </div>
    </div>

  afterOuterContent: |
    <div class="pf-v5-l-grid__item pf-m-6-col">
      <div class="pf-v5-c-card pf-m-full-height">
        <div class="pf-v5-c-card__title">
          <h2 class="pf-v5-c-card__title-text">Scan your SBOM</h2>
        </div>
        <div class="pf-v5-c-card__body">
          You can upload or copy-and-paste your Software Bill of Materials (SBOM) file to get a detailed report of dependencies, and potential vulnerabilities within your application.
          Click the <strong>Scan an SBOM</strong> button to start the analysis.
          The Trusted Content service does not store any uploaded or inspected SBOM files.
        </div>
        <div class="pf-v5-c-card__body">
          <div class="pf-v5-l-bullseye">
            <div class="pf-v5-l-bullseye__item">
              <a
                class="pf-v5-c-button pf-m-primary pf-m-display-lg"
                type="button"
                href="/scanner"
              >Scan an SBOM</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="pf-v5-l-grid__item pf-m-6-col">
      <div class="pf-v5-c-card pf-m-full-height">
        <div class="pf-v5-c-card__title">
          <h2 class="pf-v5-c-card__title-text">Getting started!</h2>
        </div>
        <div class="pf-v5-c-card__body">
          <div class="pf-v5-l-gallery pf-m-gutter">
            <div class="pf-v5-l-gallery__item">
              <a href="https://trustification.io/" target="_blank" class="pf-v5-c-button pf-m-inline pf-m-link" type="button">Project Homepage</button>
            </div>
            <div class="pf-v5-l-gallery__item">
              <a href="https://github.com/trustification/trustification/" target="_blank" class="pf-v5-c-button pf-m-inline pf-m-link" type="button">GitHub Repository</button>
            </div>
          </div>
        </div>
      </div>
    </div>

global:
  documentationUrl: https://docs.staging.trustification.dev/
  supportUrl: https://github.com/trustification/trustification/issues
