apiVersion: v1
kind: Template
metadata:
  name: spog-ui
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: spog-ui
      labels:
        app.kubernetes.io/name: spog-ui
        app.kubernetes.io/component: ui
        app.kubernetes.io/part-of: spog
    spec:
      replicas: ${{ REPLICAS }}
      selector:
        matchLabels:
          app.kubernetes.io/name: spog-ui
          app.kubernetes.io/component: ui
          app.kubernetes.io/part-of: spog
      template:
        metadata:
          labels:
            app.kubernetes.io/name: spog-ui
            app.kubernetes.io/component: ui
            app.kubernetes.io/part-of: spog
        spec:
          volumes:
            - name: endpoints
              emptyDir: {}
            - name: run
              emptyDir: {}
            - name: branding
              configMap:
                name: spog-ui-branding
          containers:
            - image: ${IMAGE}:${IMAGE_TAG}
              imagePullPolicy: ${IMAGE_PULL_POLICY}
              name: service
              env:
                - name: API_URL
                  value: "${API_URL}"
                - name: BOMBASTIC_URL
                  value: "${BOMBASTIC_URL}"
                - name: VEXINATION_URL
                  value: "${VEXINATION_URL}"
                - name: ISSUER_URL
                  value: "${ISSUER_URL}"
                - name: CLIENT_ID
                  value: "${CLIENT_ID}"
                - name: SCOPES
                  value: "${SCOPES}"
              volumeMounts:
                - name: endpoints
                  mountPath: /endpoints
                - name: branding
                  mountPath: /public/branding
                - name: run
                  mountPath: /run
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources: "${{RESOURCES}}"
              livenessProbe:
                httpGet:
                  path: /
                  port: 8080
                initialDelaySeconds: 2
              readinessProbe:
                httpGet:
                  path: /
                  port: 8080
                initialDelaySeconds: 2
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/name: spog-ui
        app.kubernetes.io/component: ui
        app.kubernetes.io/part-of: spog
      name: spog-ui
    spec:
      ports:
      - name: endpoint
        port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app.kubernetes.io/name: spog-ui
        app.kubernetes.io/component: ui
        app.kubernetes.io/part-of: spog
      type: ClusterIP
parameters:
- name: IMAGE
- name: IMAGE_TAG
- name: IMAGE_PULL_POLICY
  value: Always
- name: REPLICAS
  value: "1"
- name: API_URL
- name: BOMBASTIC_URL
- name: VEXINATION_URL
- name: CLIENT_ID
- name: ISSUER_URL
- name: SCOPES
- name: RESOURCES
  value: '{"requests": {"memory": "128Mi"}, "limits":{"memory": "128Mi"}}'
