apiVersion: v1
kind: ConfigMap
metadata:
  name: spog-ui-branding
  labels:
    app.kubernetes.io/name: spog-ui
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: spog
binaryData:
  {{- range $path, $content := .Files.Glob "files/common/**" }}
  {{ $path | quote }}: {{ $content | toJson }}
  {{- end }}
