apiVersion: apps/v1
kind: Deployment
metadata:
  name: spog-ui
  labels:
    app.kubernetes.io/name: spog-ui
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: spog
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: spog-ui
      app.kubernetes.io/component: ui
      app.kubernetes.io/part-of: spog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spog-ui
        app.kubernetes.io/component: ui
        app.kubernetes.io/part-of: spog
    spec:
      volumes:
        - name: endpoints
          emptyDir: {}
        - name: run
          emptyDir: {}
        - name: branding
          configMap:
            name: spog-ui-branding
      containers:
        - image: ghcr.io/trustification/trust-ui:{{ .Values.release }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: service
          env:
            - name: API_URL
              value: https://api.{{ .Values.domain }}
            - name: BOMBASTIC_URL
              value: https://sbom.{{ .Values.domain }}
            - name: VEXINATION_URL
              value: https://vex.{{ .Values.domain }}
            - name: ISSUER_URL
              value: {{ .Values.authentication.issuerUrl | quote }}
            - name: CLIENT_ID
              {{ include "trustification.authentication-frontend-client-id" . | nindent 14 }}
          volumeMounts:
            - name: endpoints
              mountPath: /endpoints
            - name: branding
              mountPath: /public/branding
            - name: run
              mountPath: /run
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "64Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
