{{ if .Values.collector.osv.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-osv
  labels:
    app.kubernetes.io/name: collector-osv
    app.kubernetes.io/component: collector
    app.kubernetes.io/part-of: trustification
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: collector-osv
      app.kubernetes.io/component: collector
      app.kubernetes.io/part-of: trustification
  template:
    metadata:
      labels:
        app.kubernetes.io/name: collector-osv
        app.kubernetes.io/component: collector
        app.kubernetes.io/part-of: trustification
        metrics: "true"
      annotations:
        config/checksum: {{ include (print $.Template.BasePath "/config/020-ConfigMap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: {{ .Values.config.name }}
      containers:
        - image: {{ .Values.trustImage }}:{{ .Values.release }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: service
          command: ["/trust"]
          args:
            - "collector"
            - "osv"
            - "-p"
            - "8080"
            - "--collectorist-url"
            - "http://collectorist-api"
            - "--advertise"
            - "http://collector-osv"
          env:
            - name: RUST_LOG
              value: info
            - name: INFRASTRUCTURE_ENABLED
              value: "true"
            - name: INFRASTRUCTURE_BIND
              value: "[::]:9010"
            - name: SWAGGER_UI_OIDC_ISSUER_URL
              {{ include "trustification.authentication-frontend-issuer-url" . | nindent 14 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - mountPath: /etc/config
              name: config
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9010
              protocol: TCP
              name: infra
          resources:
            {{- toYaml .Values.collector.osv.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9010
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9010
            initialDelaySeconds: 2
          startupProbe:
            httpGet:
              path: /health/startup
              port: 9010
{{ end }}
