{{ if .Values.createRoutes }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: collector-osv
    app.kubernetes.io/component: collector
    app.kubernetes.io/part-of: trustification
  name: collector-osv
spec:
  host: "osv.collector.{{ .Values.domain }}"
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: endpoint
  to:
    kind: Service
    name: collector-osv
    weight: 100
  wildcardPolicy: None
{{ end }}
