apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombastic-api
  labels:
    app.kubernetes.io/name: bombastic-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: bombastic
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: bombastic-api
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: bombastic
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bombastic-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: bombastic
      annotations:
        config/checksum: {{ include (print $.Template.BasePath "/bombastic/api/020-ConfigMap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: bombastic-api
      containers:
        - image: {{ .Values.trustImage }}:{{ .Values.release }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: service
          command: ["/trust"]
          args:
            - "bombastic"
            - "api"
            - "-p"
            - "8080"
            - "--index-mode"
            - "{{ .Values.bombastic.indexMode }}"

            {{- include "trustification.authentication-server" . | nindent 12 }}
          env:
            - name: RUST_LOG
              value: info
            - name: STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.bombastic.credentials }}"
                  key: access-key-id
            - name: STORAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.bombastic.credentials }}"
                  key: secret-access-key
            - name: STORAGE_REGION
              value: "{{ .Values.region }}"
            - name: STORAGE_BUCKET
              value: "{{ .Values.bombastic.bucket }}"
            - name: INFRASTRUCTURE_ENABLED
              value: "true"
            - name: INFRASTRUCTURE_BIND
              value: "[::]:9010"
            - name: SWAGGER_UI_OIDC_ISSUER_URL
              {{ include "trustification.authentication-frontend-issuer-url" . | nindent 14 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - mountPath: /etc/config
              name: config
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9010
              protocol: TCP
              name: infra
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9010
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9010
            initialDelaySeconds: 2
          startupProbe:
            httpGet:
              path: /health/startup
              port: 9010
